remote_theme:		BlackrockDigital/startbootstrap-clean-blog-jekyll
title:				An Affair With Thoughs...
email:manishvaishu25@gmail.com
description:        An Affair With Thoughs...
author:             Manish Prasad
baseurl:            "/"
url:                "https://manisuec.github.io"

# Social Profiles
twitter_username:   @_manish25
github_username:    manisuec

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
