remote_theme: "BlackrockDigital/startbootstrap-clean-blog-jekyll"
title: "Tech Insights"
description: "Tech Insights ..."
email: "manishvaishu25@gmail.com"
author: "Manish Prasad"
baseurl: ""
url: "https://manisuec.blog"
google_analytics: "UA-111859472-2"

# Social Profiles
twitter_username: "@_manish25"
github_username: "manisuec"

# Build settings
markdown: "kramdown"
paginate: 5
paginate_path: "/posts/page:num/"

# plugins
plugins:
  - jekyll-diagrams
  - jekyll-paginate
